Repository project-diaspora/project-diaspora, pull requests merged in 2019-12, with the labels that each got.

#13 Complete send DAI flow working + refactor
  App.js
  package-lock.json
  package.json
  screens/AddMoney.js
  screens/settings/RecoveryPhrase.js
  src/components/WalletActionButtons.js
  src/components/utils/Crypto.js
  src/context/AuthContext.js
  src/navigation/MainTabNavigator.js
  src/screens/AddCryptoScreen.js
  src/screens/ConfirmTransactionScreen.js
  src/screens/HomeScreen.js
  src/screens/RecoveryPhraseScreen.js
  src/screens/SelectAmountScreen.js
  src/screens/SelectContactScreen.js
  src/screens/SettingsScreen.js
  src/screens/SignUpScreen.js
Labels: enhancement

#11 Reviewdog ESlint integration with GitHub Actions
  .github/workflows/reviewdog.yml
  .reviewdog.yml
  babel.config.js
  package-lock.json
  package.json
  src/navigationRef.js
Labels: enhancement

#15 Update readme for react native
  README.md
Labels: documentation

#16 WIP: Added transaction context
  .eslintrc
  .github/workflows/reviewdog.yml
  App.js
  assets/images/btc.png
  assets/images/dai.png
  assets/images/eth.png
  config.js
  package-lock.json
  package.json
  shim.js
  src/api/etherScan.js
  src/components/HeaderText.js
  src/components/TransactionList.js
  src/components/WalletActionButtons.js
  src/components/__tests__/StyledText-test.js
  src/components/utils/Crypto.js
  src/constants/Currencies.js
  src/constants/Layout.js
  src/context/AuthContext.js
  src/context/TransactionContext.js
  src/context/createDataContext.js
  src/navigationRef.js
  src/screens/AddCryptoScreen.js
  src/screens/AddMoneyScreen.js
  src/screens/AuthLanding.js
  src/screens/ConfirmTransactionScreen.js
  src/screens/HomeScreen.js
  src/screens/RecoveryPhraseScreen.js
  src/screens/ResolveAuthScreen.js
  src/screens/SelectAmountScreen.js
  src/screens/SelectContactScreen.js
  src/screens/SettingsScreen.js
  src/screens/SignInScreen.js
  src/screens/SignUpScreen.js
Labels: enhancement

#18 Sign + verify calls
  app.json
  assets/images/icon.png
  assets/images/inverse-logo.png
  assets/images/logo.png
  assets/images/splash.png
  db.json
  package.json
  src/api/__tests__/backend.test.js
  src/api/backend.js
  src/components/utils/Crypto.js
  src/components/utils/__tests__/Crypto.test.js
  src/screens/AddCardScreen.js
  src/screens/AddMoneyScreen.js
  src/screens/ConfirmTransactionScreen.js
  src/screens/HomeScreen.js
  src/screens/RecoveryPhraseScreen.js
  src/screens/SelectAmountScreen.js
  src/screens/SelectContactScreen.js
  src/screens/SettingsScreen.js
  src/screens/SupportScreen.js
Labels: enhancement

#19 Small fixes for backend calls
  README.md
  src/api/backend.js
  src/context/AuthContext.js
  src/screens/SelectContactScreen.js
  src/screens/SignUpScreen.js
Labels: enhancement

#20 Fix build
  App.js
  app.json
  environment.js
  src/api/etherScan.js
Labels: enhancement

#21 Rename etherScan.js to etherscan.js
  src/api/etherscan.js
Labels: bug

#22 Fix typo
  app.json
Labels: bug
